<?php

/**
 * @file
 * Certificates core functions.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function certificates_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the certificates module.
    case 'help.page.certificates':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A certificate.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_install().
 */
function certificates_install() {
  \Drupal::configFactory()->getEditable('certificates.settings')
    ->set('certificates_url_prefix', Url::fromRoute('<front>', [], ['absolute' => TRUE]))
    ->save();
}

/**
 * Implements hook_form_alter().
 */
function certificates_form_alter(&$form, FormStateInterface $form_state) {
  $form['#attached']['library'][] = 'certificates/play';
}

/**
 * Implements hook_theme().
 */
function certificates_theme() {
  $theme = [];
  $theme['certificate'] = [
    'render element' => 'elements',
    'file' => 'certificate.page.inc',
    'template' => 'certificate',
  ];
  $theme['certificate_content_add_list'] = [
    'render element' => 'content',
    'variables' => [
      'content' => NULL
    ],
    'file' => 'certificate.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function certificates_theme_suggestions_certificate(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#certificate'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'certificate__' . $sanitized_view_mode;
  $suggestions[] = 'certificate__' . $entity->bundle();
  $suggestions[] = 'certificate__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'certificate__' . $entity->id();
  $suggestions[] = 'certificate__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
