<?php

/**
 * @file
 * Certificate Generator core functions.
 */

use Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Url;

/**
 * Implements hook_install().
 */
function certificate_generator_install() {
  // Set default values for config which require dynamic values.
  \Drupal::configFactory()->getEditable('certificate_generator.settings')
    ->set('certificate_generator_url_prefix', Url::fromRoute('<front>', [], ['absolute' => TRUE]))
    ->save();
}

/**
 * Implements hook_preprocess_page().
 */
function certificate_generator_preprocess_page(array &$variables) {
  $uri = \Drupal::request()->getRequestUri();

  // Return the correct library based on the uri
  switch ($uri) {
    case '/ixr-course-complete-certificate':
      $variables['#attached']['library'][] = 'certificate_generator/interact_course_complete';
        break;
  }

}

/**
 * Implements hook_form_alter().
 */
function certificate_generator_form_alter(&$form, FormStateInterface $form_state) {
  // $form['#attached']['library'][] = 'certificate_generator/play';
  $form['#attached']['library'][] = 'certificate_generator/jspdf';
}

/**
 * Implements hook_theme().
 */
function certificate_generator_theme(array $existing, $type, $theme, $path) {
  return [
    'certificate_generator_playground' => [
      'render element' => 'form',
      'template' => 'playground',
      'variables' => [
        'create_form' => NULL
      ]
    ]
  ];
}
